### ISSUE TITLE
How to get Raw data 

### ISSUE THREAD

**Issue by aishwarya85** [eflyjason/php-simple-whois-parser#1]
hi

what to do if i want to get whois raw data in result.

PLAIN WHO IS DATA :smiley:

**Comment by hesyifei** [comment]
you mean get original plain whois data or?

**Comment by aishwarya85** [comment]
yes plain whois data

**Comment by hesyifei** [comment]
use this: :+1: 

```
<?php
require_once 'whois.php';
$whoisClass = new Whois;
$domain = "yourdomain.com";
echo $whoisClass->query($domain, 'text');
?>
```

**Comment by aishwarya85** [comment]
but in that its displaying all in line...

i want it in good readable manner some thing like line break :confused:

**Comment by hesyifei** [comment]
oh, try add a `pre` tag to it: :smile: 

```
require_once 'whois.php';
$whoisClass = new Whois;
$domain = "yourdomain.com";
echo "<pre>".$whoisClass->query($domain, 'text')."</pre>";
```

**Comment by aishwarya85** [comment]
nice it worked :+1: 

and one more question...

in display into aaray ...can i get line break??

where to do that???

**Comment by hesyifei** [comment]
just use `explode` function~

```
require_once 'whois.php';
$whoisClass = new Whois;
$domain = "yourdomain.com";
$result = $whoisClass->query($domain, 'text');
$resultArr = explode("\n", $result);
var_dump($resultArr);
```

**Comment by aishwarya85** [comment]
no all array comes in same line...
"array(67) { [0]=> string(22) "Domain Name:HELLO.ORG " [1]=> string(25) "Domain ID: D3298119-LROR " [2]=> string(36) "Creation Date: 1996-10-03T04:00:00Z " [3]=> string(35) "Updated Date: 2015-08-11T19:40:58Z " [4]=> string(43) "Registry Expiry Date: 2017-10-02T04:00:00Z " [5]=> string(44) "Sponsoring Registrar:Tucows Inc. (R11-LROR) " [6]=> string(33) "Sponsoring Registrar IANA ID: 69 " [7]=> string(15) "WHOIS Server: " [8]=> string(15) "Referral URL: " [9]=> string(49) "Domain Status: ok -- http://www.icann.org/epp#ok " [10]=> string(31) "Registrant ID:tuEkrZfFyo2yaAUd " [11]=> string(32) "Registrant Name:Chung Ming Shih " [12]=> string(31) "Registrant Organization:Nougen " [13]=> string(43) "Registrant Street: 1st Floor #38, 119 Lane " [14]=> string(42) "Registrant Street: Sect. 4, Roosevelt Rd. " [15]=> string(23) "Registrant City:Taipei " [16]=> string(33) "Registrant State/Province:Taiwan " [17]=> string(29) "Registrant Postal Code:10673 " [18]=> string(22) "Registrant Country:TW " [19]=> string(32) "Registrant Phone:+886.930916996 " [20]=> string(23) "Registrant Phone Ext: " [21]=> string(17) "Registrant Fax: " [22]=> string(21) "Registrant Fax Ext: " [23]=> string(31) "Registrant Email:min@hello.org " [24]=> string(26) "Admin ID:tu8T0MYMrT5G8IvM " [25]=> string(27) "Admin Name:Chung Ming Shih " [26]=> string(26) "Admin Organization:Nougen " [27]=> string(38) "Admin Street: 1st Floor #38, 119 Lane " [28]=> string(37) "Admin Street: Sect. 4, Roosevelt Rd. " [29]=> string(18) "Admin City:Taipei " [30]=> string(28) "Admin State/Province:Taiwan " [31]=> string(24) "Admin Postal Code:10673 " [32]=> string(17) "Admin Country:TW " [33]=> string(27) "Admin Phone:+886.930916996 " [34]=> string(18) "Admin Phone Ext: " [35]=> string(12) "Admin Fax: " [36]=> string(16) "Admin Fax Ext: " [37]=> string(26) "Admin Email:min@hello.org " [38]=> string(25) "Tech ID:tuj3T1Wges519Sez " [39]=> string(26) "Tech Name:Rick Macdougall " [40]=> string(36) "Tech Organization:Nougen Canada Inc " [41]=> string(32) "Tech Street: 178 cloverdale ave " [42]=> string(19) "Tech City:Hamilton " [43]=> string(23) "Tech State/Province:ON " [44]=> string(24) "Tech Postal Code:L8K4M3 " [45]=> string(16) "Tech Country:CA " [46]=> string(25) "Tech Phone:+1.9055480738 " [47]=> string(17) "Tech Phone Ext: " [48]=> string(11) "Tech Fax: " [49]=> string(15) "Tech Fax Ext: " [50]=> string(28) "Tech Email:rickm@nougen.com " [51]=> string(32) "Name Server:NS1.DNSMADEEASY.COM " [52]=> string(32) "Name Server:NS4.DNSMADEEASY.COM " [53]=> string(32) "Name Server:NS3.DNSMADEEASY.COM " [54]=> string(32) "Name Server:NS0.DNSMADEEASY.COM " [55]=> string(32) "Name Server:NS2.DNSMADEEASY.COM " [56]=> string(14) "Name Server: " [57]=> string(14) "Name Server: " [58]=> string(14) "Name Server: " [59]=> string(14) "Name Server: " [60]=> string(14) "Name Server: " [61]=> string(14) "Name Server: " [62]=> string(14) "Name Server: " [63]=> string(14) "Name Server: " [64]=> string(16) "DNSSEC:Unsigned " [65]=> string(1) " " [66]=> string(1277) "Access to Public Interest Registry WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the Public Interest Registry registry database. The data in this record is provided by Public Interest Registry for informational purposes only, and Public Interest Registry does not guarantee its accuracy. This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to(a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. Public Interest Registry reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy. For more information on Whois status codes, please visit https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en." }"

**Comment by hesyifei** [comment]
actually you can see source code of the page directly if you want to see formatted array :)

**Comment by aishwarya85** [comment]
ya thats true...anyways...thanks for your help...

at present in url m getting
whoisp1/?domain=hello.org

can i cahnge it to
whoisp1/domain/hello.org
OR
whoisp1/hello.org

if you have any idea

**Comment by aishwarya85** [comment]
actually i am new to php language so having lots of questions.... :smile:

**Comment by hesyifei** [comment]
if you want to do that you have to use e.g. `.htaccess` for Apache. You can google for more information about `url rewrite` and learn it. It's quite complicated actually and not related to PHP mostly. :)

**Comment by aishwarya85** [comment]
ohhh thanks for guide lines...

one completely last question..

http://whois.icann.org/en/lookup?name=hello.org

how he displayed this things seperately?

can we do with our code in same way?

help will be really appreciated heartly. :sweat_smile:

**Comment by hesyifei** [comment]
see this result getting back from parser (code: `print_r($whoisClass->query($domain));`):

```
Array
(
    [domain] => github.com
    [id] => 1264983250_DOMAIN_COM-VRSN
    [whois_server] => Array
        (
            [0] => whois.markmonitor.com
        )

    [registrar_url] => Array
        (
            [0] => http://www.markmonitor.com
        )

    [updated] => Array
        (
            [0] => 2015-01-08T04:00:18-0800
        )

    [created] => Array
        (
            [0] => 2007-10-09T11:20:50-0700
        )

    [expires] => Array
        (
            [0] => 2020-10-09T11:20:50-0700
        )

    [registrar] => Array
        (
            [0] => MarkMonitor, Inc.
        )

    [status] => Array
        (
            [0] => clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)
            [1] => clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)
            [2] => clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)
        )

    [dns] => Array
        (
            [0] => ns1.p16.dynect.net
            [1] => ns2.p16.dynect.net
            [2] => ns3.p16.dynect.net
            [3] => ns4.p16.dynect.net
        )

    [created_parsed] => Array
        (
            [year] => 2007
            [month] => 10
            [day] => 9
            [hour] => 11
            [minute] => 20
            [second] => 50
            [fraction] => 0
            [warning_count] => 0
            [warnings] => Array
                (
                )

            [error_count] => 0
            [errors] => Array
                (
                )

            [is_localtime] => 1
            [zone_type] => 1
            [zone] => 420
            [is_dst] => 
        )

    [created_parsed_string] => 2007-10-09 11:20:50
    [expires_parsed] => Array
        (
            [year] => 2020
            [month] => 10
            [day] => 9
            [hour] => 11
            [minute] => 20
            [second] => 50
            [fraction] => 0
            [warning_count] => 0
            [warnings] => Array
                (
                )

            [error_count] => 0
            [errors] => Array
                (
                )

            [is_localtime] => 1
            [zone_type] => 1
            [zone] => 420
            [is_dst] => 
        )

    [expires_parsed_string] => 2020-10-09 11:20:50
    [updated_parsed] => Array
        (
            [year] => 2015
            [month] => 1
            [day] => 8
            [hour] => 4
            [minute] => 0
            [second] => 18
            [fraction] => 0
            [warning_count] => 0
            [warnings] => Array
                (
                )

            [error_count] => 0
            [errors] => Array
                (
                )

            [is_localtime] => 1
            [zone_type] => 1
            [zone] => 480
            [is_dst] => 
        )

    [updated_parsed_string] => 2015-01-08 04:00:18
    [registrant] => Array
        (
            [name] => GitHub Hostmaster
            [organization] => GitHub, Inc.
            [address] => Array
                (
                    [0] => 88 Colin P Kelly Jr St,
                )

            [city] => San Francisco
            [state_province] => CA
            [postal_code] => 94107
            [country] => US
            [phone] => +1.4157354488
            [email] => hostmaster@github.com
            [completely_address] => 88 Colin P Kelly Jr St,
        )

    [admin] => Array
        (
            [name] => GitHub Hostmaster
            [organization] => GitHub, Inc.
            [address] => Array
                (
                    [0] => 88 Colin P Kelly Jr St,
                )

            [city] => San Francisco
            [state_province] => CA
            [postal_code] => 94107
            [country] => US
            [phone] => +1.4157354488
            [email] => hostmaster@github.com
            [completely_address] => 88 Colin P Kelly Jr St,
        )

    [tech] => Array
        (
            [name] => GitHub Hostmaster
            [organization] => GitHub, Inc.
            [address] => Array
                (
                    [0] => 88 Colin P Kelly Jr St,
                )

            [city] => San Francisco
            [state_province] => CA
            [postal_code] => 94107
            [country] => US
            [phone] => +1.4157354488
            [email] => hostmaster@github.com
            [completely_address] => 88 Colin P Kelly Jr St,
        )

)
```

Once after you get the parsed Whois data (it have been separated), you can simply get e.g. `$result["id"]` for it's domain ID. And then `echo` it in a page and that's all. :)

PS: I'm not native english speaker so sorry for bad english, hope you understand what I mean :smile:

**Comment by aishwarya85** [comment]
no no you are very good at english, who said that you have bad english:question: 

i am completely able to understand what you saying :heart:

**Comment by hesyifei** [comment]
:smile: so any other question? :+1:

**Comment by aishwarya85** [comment]
wait let me check ...just a moment :smiley:

**Comment by aishwarya85** [comment]
i just want to show 
[admin] => Array
        (
            [name] => GitHub Hostmaster
            [organization] => GitHub, Inc.
            [address] => Array
                (
                    [0] => 88 Colin P Kelly Jr St,
                )

            [city] => San Francisco
            [state_province] => CA
            [postal_code] => 94107
            [country] => US
            [phone] => +1.4157354488
            [email] => hostmaster@github.com
            [completely_address] => 88 Colin P Kelly Jr St,
        )


this part so what should i write in a code to echo is on screen??

**Comment by hesyifei** [comment]
you can simply use `print_r($result["admin"])` (`print_r` is a function to print out array, same as `var_dump`, you need to see formatted on in source code)
or if you want to get exactly admin's city, you can try `echo $result["admin"]["city"]` :smile:

**Comment by aishwarya85** [comment]
sorry but both code not working...

m trying to get seperate data from last two hours but no result :disappointed:

**Comment by aishwarya85** [comment]
Warning: Illegal string offset 'city' in C:\xampp\htdocs\whoisp1\index.php on line 43
D

this error for echo code

Warning: Illegal string offset 'admin' in C:\xampp\htdocs\whoisp1\index.php on line 44
D

this error print_r code

**Comment by hesyifei** [comment]
remember you have to use `$whoisClass->query($domain)` for parsed result
cause just now you are getting plain text by `$whoisClass->query($domain, 'text');`

**Comment by aishwarya85** [comment]
oh yes there was my mistake but still echo function not working...

this is my code

```
require_once 'whois.php';
$whoisClass = new Whois;

$domain = $_GET['domain'];

$domain = str_replace("http://", "", $domain);
$domain = str_replace("https://", "", $domain);
$domain = str_replace("www.", "", $domain);
$domain = explode("/", $domain, 2)[0];

$domain = strtolower($domain);
$domain = htmlspecialchars($domain);

$result = $whoisClass->query($domain);

print_r($result["admin"]);
```

but echo function not working

**Comment by aishwarya85** [comment]
```
echo '<pre>';
print_r($result["admin"]);
echo '</pre>';
```

and using this function i got array in good readable manner as in source code :grinning:

**Comment by hesyifei** [comment]
yeah, `pre` tag is same effect as watching source code :)

you mean `echo $result["admin"]["city"]` not working?

**Comment by aishwarya85** [comment]
yes echo       

             echo $result["admin"]["city"]

not working

**Comment by hesyifei** [comment]
let me check first

**Comment by hesyifei** [comment]
which domain you are checking?

**Comment by hesyifei** [comment]
just to make sure, do you add `;` to finish the line?

```
echo $result["admin"]["city"];
```

**Comment by aishwarya85** [comment]
yes it worked :+1: 

thanks a lot :bow:

**Comment by aishwarya85** [comment]
can i get your mail id on aishwaryataneja85@gmail.com

**Comment by hesyifei** [comment]
? what do you mean

**Comment by aishwarya85** [comment]
to contact you in future ...can i get your email address

**Comment by hesyifei** [comment]
oh ok~ eflyjason@gmail.com :)
