### ISSUE TITLE
Can we find ip data from this?

### ISSUE THREAD

**Issue by jackchurchill85** [eflyjason/php-simple-whois-parser#2]
hello eflyjason

is it possible to get ip-address data from this script?

   example: http://who.is/whois-ip/ip-address/198.252.206.140

**Comment by aishwarya85** [comment]
it is possible by speedywhois.com

visit there..

**Comment by hesyifei** [comment]
i will add this as feature of next version. wait please! :)

**Comment by jackchurchill85** [comment]
okay thanks :)
