### ISSUE TITLE
Take .com automatically

### ISSUE THREAD

**Issue by ziyamodi** [eflyjason/php-simple-whois-parser#5]
Hello eflyjason,

I saw your parser its good :)

I want to do some extra thing with it like if some one types google it shows error "THIS IS NOT A VALID INPUT". 

Is it possible that it must take .com automatically when nothing is entered after google?

**Comment by hesyifei** [comment]
You can try add some code to detect if the input domain has `.` inside. If you still don't know how, I will try to help you.

**Comment by ziyamodi** [comment]
Ya because i am newbie for php :wink:

**Comment by hesyifei** [comment]
If your domain value is `$domain`, try:

```
if (strpos($domain, '.') !== false) {
    $domain .= ".com";
}
```

This will add `".com"` to the domain if there is no `.` inside `$domain`

**Comment by ziyamodi** [comment]
```
if (strpos($domain, '.') !== false) {
    $domain .= ".com";
}
```

This didn't work...

But this worked

```
if (strpos($domain, '.') == false) {
    $domain .= ".com";
}
```

**Comment by eflyjason** [comment]
Ah yes. Sorry my code is wrong
